[package]
name = "brdgme-game"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { path = "../std" }
brdgme-markup = { path = "../markup" }
chrono = "*"
serde = "*"
combine = "*"
