[package]
name = "brdgme-game"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
time = "^0.1.35"
serde = "^0.8.10"
brdgme-markup = { path = "../markup" }
combine = { git = "https://github.com/Marwes/combine.git" }
